### PR TITLE
Ubuntu 16.04 VM setup in AWS

### PR DESCRIPTION
**Pull request by cole-wustl**
Add 'aws' folder in lab-setup/ with instructions on how to set up a SEEDUbuntu-16.04 VM in AWS.
- includes instructions on how a new AWS "community" AMI was built from the baseline SEED VM
- includes instructions for launching an EC2 instance running the new AMI
- AMI supports both SSH and remote-desktop logins (tested under Windows only).

### CODE REVIEW

**Comment by kevin-w-du** [comment]
This is great. Thanks a lot for your contribution.

**Comment by kevin-w-du** [comment]
I also added the link to this instruction to the SEED website: https://seedsecuritylabs.org/lab_env.html.

**Comment by cole-wustl** [comment]
Thank you!  I've used the SEED labs for several semesters to teach security, so I'm glad to be able to contribute and I appreciate the opportunity provided by your open-sourcing everything.

Feel free to direct users to me for support/issues with the AWS setup if you want, by the way-- happy to keep improving it and fixing any bugs.

**Comment by kevin-w-du** [comment]
I will definitely direct AWS related questions/issues to you. Providing AWS support is one of the top items on my list. Many students' computers are not powerful enough to run VMs, AWS solves that problem. I believe more and people will use cloud to work on SEED labs, so providing cloud support is essential.  Thanks for taking the lead on this.

**Pull request merged**
