### PR TITLE
Add Web_Clickjacking lab.

### PR DESCRIPTION
**Pull request by cole-wustl**
Here is an initial cut at the lab.  The lab was developed by students Collin Howland, Faith Letzkus, and Julio Trujillo for an Intro to Security course project, and I edited the instructions.  Notes:
 
(1) I've credited the 3 students in the copyright, but let me know if I should handle the credit differently.

(2) I'll send solutions separately.

(3) I've tested the lab on the Ubuntu 20.04 SEED VM and it all worked.  However, the current build procedure is not consistent with other Web labs or the 20.04 platform: it requires running a web server, and it currently does that via Flask instead of Apache like the other Web labs.

### CODE REVIEW

**Comment by kevin-w-du** [comment]
This is great. The copyright is good (copyright goes to the original developers).  I will take a look at this, test it myself, and I may revise it. Once it is ready, I will add it to the SEED website so it can reach SEED users. Thanks for the contribution.

**Comment by cole-wustl** [comment]
Great, thank you!  The students will be happy to hear this too.  :-)

**Comment by kevin-w-du** [comment]
A quick comment: In SEED 2.0, any server needed for a SEED lab must be running inside a container. This is important because I am gradually removing the dependence on the SEED VM, so the labs can be conducted on any VM or physical computer. This lab can follow what we did for the DNS_Rebinding lab, because that lab also uses a flask server (not Apache). I already have a Flask docker image, which can be used as the base image.  Porting your current setup to container setup should be quite easy.  If you students can do that and update the lab description, it will be great.

Since the lab requires a browser, so the client machine will be using VM, but I believe any VM can be the client.

**Comment by kevin-w-du** [comment]
After reading the document, it seems to me that the reason for using Flask is to be able to set the CSP and X-Frame-Options header. If that is the reason, I would suggest using Apache, so it can be consistent with the XSS lab, which also sets CSP header.  

In terms of containers, I suggest using two containers, one for hosting the attacker's website, and the other for hosting the benign website. They can both use handsonsecurity/seed-server:apache or handsonsecurity/seed-server:apach-php as the basis.  If you prefer to use Flask, you can use seed-server:flask as the base.

**Pull request merged**
