### PR TITLE
AWS build of SEED-Ubuntu20.04

### PR DESCRIPTION
**Pull request by cole-wustl**
I wrote up instructions similar to the ones for the Google Cloud that show the steps of setting up an instance on AWS, then invoking the exact same install script as for Google Cloud (with identical instructions copy-and-pasted from the Google Cloud README file).

Possible updates to discuss:
* In the current instructions, the user is burdened with creating the "seed" user, adding it to the "sudo" group, and switching to the "seed" account; this could be put into the install.sh script instead.  
* I have only mirrored the instructions currently in the Google Cloud README, so I have not added anything to handle copying /etc/hosts or .bashrc .

### CODE REVIEW

**Comment by kevin-w-du** [comment]
Thanks. This is great. I decided not to include /etc/hosts. I will modify each lab description, so students will manually add the mappings to the host file when they do the lab. I was afraid that cloud may put something in that file (Google cloud does add an entry), and I don't want to remove those entries.

**Comment by kevin-w-du** [comment]
AWS does allow us to build an AMI from our instance, and this AMI can be made public and made available from the community AMI. I tried it, and it works (Google does not have this option). Once I finished testing all the labs, we can make one. This will make students' lives even easier. Thanks for the help.

**Comment by cole-wustl** [comment]
Ah OK, that makes sense about /etc/hosts.  That might be better pedagogically anyway-- previous instructions, as you know, included pointers to /etc/hosts to tell students what changes were necessary, but I think many students just skimmed right over those parts when they realized they didn't actually have to make any changes to the file.  This will force them to understand, or at least look at, the changes.

**Comment by cole-wustl** [comment]
Yes, it is a nice feature to be able to create the AMI from an instance, and as long as you create it from a running instance, all configs are saved in the new AMI.  I guess the advantage of the stock Ubuntu20.04 image is that it's easier to find and more mainstream, but the community ones aren't too hard to find either, and zero config for students is an attractive option of course.

**Comment by cole-wustl** [comment]
Do you think we should pull the creation of the "seed" account into the install.sh script, or does it not matter if we're going to create a final-result AMI?

**Comment by kevin-w-du** [comment]
Initially, I did put that in the script, but google cloud has a much easier way to do that (in the manual), so I removed it. For AWS, I was looking for something similar, but there is none, so we should add that to the script. I wrote down some notes on this issue: 

- Use the following to add an account and password
  ```
  sudo useradd -m -s /bin/bash seed
  ```
  There is no need to add a password for this account. We will use public key for authentication.

- Enable `sudo` for the `seed` account: We need to change the following files
  ```
  add seed to the sudo group in /etc/group
  add a file to the /etc/sudoers.d/ (to disable password prompt)
  ```

- Copy the .ssh folder from /home/ubuntu so we can ssh into the `seed` account using public key
  ```
  sudo cp -r /home/ubuntu/.sh  /home/seed
  sudo chown seed /home/seed/.ssh/*
  sudo chgrp seed /home/seed/.ssh/*
  ```

**Comment by kevin-w-du** [comment]
I will see how it goes with other clouds (some professors in China are trying clouds in China). Once I get a bigger picture, I will improve the `install.sh` script and decide a unified way to add `seed` to the VM.

**Comment by cole-wustl** [comment]
OK sounds good, thank you.  Good idea to add to the sudoers file also; I'd only added seed to the sudo group in the AWS instructions I posted.

**Pull request merged**
